### ISSUE TITLE
[bug] fails to play on Safari

### ISSUE THREAD

**Issue by TBD** [bryc/ahx-web-player#3]
**problem:** as Safari is using prefixed AudioContext it fails to play

**solution:** in ahx.js:1312 use ```new (window.AudioContext || window.webkitAudioContext)()``` to create this.AudioContext and remove the check in AHXMaster()

**Comment by bryc** [comment]
Adding `window.AudioContext = window.AudioContext || window.webkitAudioContext;` to [AHXMaster()](https://github.com/bryc/ahx-web-player/blob/master/ahx.js#L45) should fix that issue.
Can you test?

**Comment by TBD** [comment]
using only AHXMasterWebKit and `this.AudioContext = new (window.AudioContext || window.webkitAudioContext)();` works

tested on
* Safari - works
* Firefox - works
* Chrome - needs a button to init WebAHX.Master from a user action

**Comment by bryc** [comment]
715fdf0 should fix it. but apple should be using  `AudioContext` by now. :pensive:
